### ISSUE TITLE
BONUS SW: Clue validation

### ISSUE THREAD

**Issue by aeciorc** [hatchways/team-fettuccini#26]
-  Spymasters shouldn't be allowed to give a clue that is identical to or contains a word on the board (and vice-versa) 

E.g: If "pineapple" is on the board, "pine" would be an invalid clue (and vice-versa)

**Comment by Flaagrah** [comment]
Even if we do that, it would still be easy for the user to use some sort of superficial encryption like indicating 2 words by alternating the letters (for example, "pine" and "cone" could hinted with "pcionnee) or removing a letter (pincon). The only way around this is to verify the word through a dictionary stored in memory. If we do that, I can also implement an autocomplete algorithm just for the sake of it (although I don't think it would add much to the game).

**Comment by aeciorc** [comment]
That's an interesting idea. I wasn't planning to go this deep but wouldn't mind that either. 250k 6 character words in a javascript object occupy just about 32 Mb, so that's pretty feasible. You don't even need to check each clue actually, you could assume all clues are valid unless an the opponent reports it, and only then bother to check for its validity.
